### ISSUE TITLE
Cannot find module 'cryptonote-util'

### ISSUE THREAD

**Issue by micron10** [Snipa22/xmr-node-proxy#22]
Hi 
I try with fresh instaled ubuntu 17.04 but in log i see this error 
Please help 

1|proxy    | 2017-08-08 08:29 +03:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/micron/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)

**Comment by micron10** [comment]
Problem is hear may be this proxy not work on ubuntu 17.04

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/micron/xmr-node-proxy/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:115: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/micron/xmr-node-proxy/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/micron/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-30-generic
gyp ERR! command "/home/micron/.nvm/versions/node/v8.2.1/bin/node" "/home/micron/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/micron/xmr-node-proxy/node_modules/cryptonote-util
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> multi-hashing@0.0.10 install /home/micron/xmr-node-proxy/node_modules/multi-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/micron/xmr-node-proxy/node_modules/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/multihashing.o
../multihashing.cc: In constructor ‘CNAsyncWorker::CNAsyncWorker(Nan::Callback*, char*, uint32_t)’:
../multihashing.cc:80:16: warning: ‘CNAsyncWorker::input’ will be initialized after [-Wreorder]
         char * input;
                ^~~~~


m.

**Comment by Snipa22** [comment]
Ubuntu 17.04 is not supported at this time, please use 16.04 LTS for any bug reports, and esnure you've installed the correct version of NodeJS.
